# Generated by Django 4.1.1 on 2022-09-15 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(unique=True)),
                ('code', models.IntegerField()),
                ('tag', models.CharField(max_length=150)),
                ('timezone', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='MassageList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('filters', models.CharField(max_length=150)),
                ('end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=150)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.clients')),
                ('massage_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.massagelist')),
            ],
        ),
    ]
